### ISSUE TITLE
Broken 夏色DIARY -Summer Dazzlin' Vacation miX- GRV

### ISSUE THREAD

**Issue by Shishiwaka** [TsFreddie/KSHConvertFix#4]
夏色DIARY -Summer Dazzlin' Vacation miX- GRV is one of the few songs in SDVX that has an INF/GRV/etc mashup alternative version. 
The normal song plays without the mashup track playing over it. Affects both USC and KSM. 

Khamen Break is another one of these types of songs, yet it plays fine in both.

**Comment by TsFreddie** [comment]
Forgot about AudioSwitch effect on the laser. Adding it now. But please do note that these can still break is USC since USC have trouble switching audio track back.

(But USC's AudioSwitch effect is using my code, so technically still my fault? I'll try to fix that in USC later.)

**Comment by TsFreddie** [comment]
Update Pack 2 has been released which added laser AudioSwitch effects.

**Comment by TsFreddie** [comment]
Fun fact that I found while fixing the script:
夏色DIARY has a section of unused vocal effect in measure 75. You can hear it in music_fx.ogg, but you can't hear it in the chart or in ac.

edit: you can probably hear it in USC tho, because USC might not be able to switch back to the original track when there is no laser.
