### ISSUE TITLE
Broken April Fools songs

### ISSUE THREAD

**Issue by Shishiwaka** [TsFreddie/KSHConvertFix#5]
The Grace and Maxima tutorial songs for their April Fools are both broken in both KSM and USC. 
Originally it wouldn't show up at all in USC until a recent update, but now it displays glitched up text in USC. 
It displays normally in KSM, but the song immediately ends when playing it in either sims. 
![Grace](https://user-images.githubusercontent.com/17868018/81037822-4cd1a100-8e61-11ea-9b88-676b849cb63e.jpg)

**Comment by magiruuvelvet** [comment]
That's interesting, because those 2 carts are working perfectly fine for me in KSM 1.70a. If you downloaded the carts from GitHub make sure they have the correct line endings. KSM needs **DOS** line endings, git or GitHub may have changed them to **UNIX** line endings. KSM can't handle that. For USC I'm not sure.

**Comment by TsFreddie** [comment]
Don't know why they don't show up in USC. But camera work in USC is not 1:1 with KSM anyway, not worth playing those on USC.

Also April Fool's charts camera work are using 1.70 tilt.

**Comment by TsFreddie** [comment]
fixed by https://github.com/TsFreddie/KSHConvertFix/commit/0ec04536e81902b7a0c784eca81e2f1fc6fd3df7
